package igu;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Carta extends javax.swing.JFrame {

    /**
     * Creates new form Eventos
     */
    public Carta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        menuDesp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioText = new javax.swing.JLabel();
        usuarioTextBox = new javax.swing.JScrollPane();
        usuarioTextPanel = new javax.swing.JTextPane();
        separador1 = new javax.swing.JSeparator();
        contrasaenaText = new javax.swing.JLabel();
        contrasenaBox = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        enviarButton = new javax.swing.JButton();
        barraSuperior = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        atrasIcon = new javax.swing.JLabel();
        atrasText = new javax.swing.JLabel();
        menuCarta = new javax.swing.JTextField();
        menu = new javax.swing.JPanel();
        cartaDulceText = new javax.swing.JLabel();
        producto1 = new javax.swing.JLabel();
        producto2 = new javax.swing.JLabel();
        producto3 = new javax.swing.JLabel();
        producto4 = new javax.swing.JLabel();
        producto5 = new javax.swing.JLabel();
        fineLine1 = new javax.swing.JLabel();
        fineLine2 = new javax.swing.JLabel();
        fineLine3 = new javax.swing.JLabel();
        fineLine4 = new javax.swing.JLabel();
        cartaSaladaText = new javax.swing.JLabel();
        producto6 = new javax.swing.JLabel();
        underlineProducto6 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        login.add(menuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        login.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        usuarioText.setBackground(new java.awt.Color(102, 51, 0));
        usuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(120, 77, 60));
        usuarioText.setText("Usuario:");
        usuarioText.setAlignmentX(20.0F);
        login.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        usuarioTextBox.setBorder(null);

        usuarioTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        usuarioTextPanel.setBorder(null);
        usuarioTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        usuarioTextPanel.setText("Ingrese su usuario o email");
        usuarioTextPanel.setAlignmentX(20.0F);
        usuarioTextBox.setViewportView(usuarioTextPanel);

        login.add(usuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        separador1.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        contrasaenaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        contrasaenaText.setForeground(new java.awt.Color(120, 77, 60));
        contrasaenaText.setText("Contraseña:");
        contrasaenaText.setAlignmentX(20.0F);
        login.add(contrasaenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        contrasenaBox.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaBox.setText("jPasswordField1");
        contrasenaBox.setAlignmentX(20.0F);
        contrasenaBox.setBorder(null);
        contrasenaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaBoxActionPerformed(evt);
            }
        });
        login.add(contrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        enviarButton.setBackground(new java.awt.Color(120, 77, 60));
        enviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Enviar");
        enviarButton.setAlignmentX(20.0F);
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        login.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        barraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        barraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        barraSuperior.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        barraSuperior.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        atrasIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\retroceder.png")); // NOI18N
        atrasIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasIconMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        atrasText.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        atrasText.setForeground(new java.awt.Color(102, 102, 102));
        atrasText.setText("ATRÁS");
        atrasText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasTextMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        menuCarta.setBackground(new java.awt.Color(255, 255, 255));
        menuCarta.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        menuCarta.setForeground(new java.awt.Color(120, 77, 60));
        menuCarta.setText("MENÚ");
        menuCarta.setBorder(null);
        menuCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCartaActionPerformed(evt);
            }
        });
        barraSuperior.add(menuCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        getContentPane().add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartaDulceText.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        cartaDulceText.setText("Carta         Dulce");
        menu.add(cartaDulceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 51, 150, 40));

        producto1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        producto1.setText("1. Dónut Clásico..............1´50€");
        menu.add(producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, -1));

        producto2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        producto2.setText("2. Dónut de Chocolate....1´70€");
        menu.add(producto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 121, 200, 20));

        producto3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        producto3.setText("3. Dónut de Crema..........1´70€");
        menu.add(producto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        producto4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        producto4.setText("4. Gofre Clásico...............2´00€");
        menu.add(producto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        producto5.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        producto5.setText("5. Crepé Dulce................2´00€");
        menu.add(producto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, -1));

        fineLine1.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        fineLine1.setText("Añade cualquier Topping por  2€:");
        menu.add(fineLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, -1));

        fineLine2.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        fineLine2.setText("- Nutella");
        menu.add(fineLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, -1));

        fineLine3.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        fineLine3.setText("- Chocolate Blanco");
        menu.add(fineLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, -1));

        fineLine4.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        fineLine4.setText("- Dulce de Leche");
        menu.add(fineLine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, -1));

        cartaSaladaText.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        cartaSaladaText.setText("Carta         Salada");
        menu.add(cartaSaladaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 30));

        producto6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        producto6.setText("1. Sándwich");
        menu.add(producto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 200, -1));

        underlineProducto6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        underlineProducto6.setText("Mixto........1´50€");
        menu.add(underlineProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, -1));

        jLabel46.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel46.setText("2. Sándwich");
        menu.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 200, -1));

        jLabel31.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel31.setText("3. Bocadillo Jamón............1´90€");
        menu.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 220, -1));

        jLabel32.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel32.setText("4. Crepé Salado.................2´00€");
        menu.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, -1));

        jLabel47.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel47.setText("5. Croissant Jamón ");
        menu.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 210, -1));

        jLabel33.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel33.setText("York y Queso...............2´10€");
        menu.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 210, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel7.setText("3. Café Ristretto.............1´50€");
        menu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, -1));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel8.setText("1. Expresso......................1´20€");
        menu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 200, -1));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel9.setText("2. Cortado........................1´20€");
        menu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 200, -1));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel10.setText("6. Café con Leche............1´50€");
        menu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 200, -1));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel11.setText("4. Café Largo..................1´50€");
        menu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 200, -1));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setText("5. Latte Macchiato.........1´50€");
        menu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 200, -1));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setText("9. Café Bombón...............1´75€");
        menu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, -1));

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel14.setText("7. Capuccino....................1´50€");
        menu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 200, -1));

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel15.setText("8. Café Mocca.................1´50€");
        menu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 200, -1));

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel16.setText("12. Carajillo.....................1´75€");
        menu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 200, -1));

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel17.setText("10. Café Vienés...............1´75€");
        menu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 200, -1));

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel18.setText("11. Café Irlandés.............1´75€");
        menu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 200, -1));

        jLabel34.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel34.setText("13. Café Americano.........1´80€");
        menu.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 200, -1));

        jLabel35.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel35.setText("14. Frappé.......................1´80€");
        menu.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 200, -1));

        jLabel36.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel36.setText("15. Descafeinado............1´00€");
        menu.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 200, -1));

        jLabel37.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel37.setText("16. Azteca..........1´50€");
        menu.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 200, -1));

        jLabel39.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel39.setText("14. Avellana.......1´50€");
        menu.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 200, -1));

        jLabel40.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel40.setText("16. Infusiones....1´00€");
        menu.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 200, -1));

        jLabel55.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel55.setText("15. Nube............1´50€");
        menu.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 200, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel2.setText("Carta           Infantil");
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 150, 30));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel3.setText("Nuestro Café");
        menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 100, 30));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel4.setText("Platos         Especiales");
        menu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 40));

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel19.setText("1. Pan sin Gluten");
        menu.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 200, -1));

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel20.setText("2. Pastel de la casa ");
        menu.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, -1));

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel21.setText("    sin azúcar..................2´00€");
        menu.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 200, -1));

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel22.setText("Frescas Variadas......3´00€");
        menu.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 200, -1));

        jLabel23.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel23.setText("    sin azúcar..................1´85€");
        menu.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 200, -1));

        jLabel30.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel30.setText("Vegetal.......1´50€");
        menu.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 200, -1));

        jLabel48.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel48.setText("Menú Coffee Monster ");
        menu.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 200, -1));

        jLabel49.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel49.setText("Infantil...........................4´00€");
        menu.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 200, -1));

        jLabel50.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel50.setText("- Batido/Refresco/");
        menu.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 200, -1));

        jLabel51.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel51.setText("- Producto Dulce ó Salado");
        menu.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 200, -1));

        jLabel52.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel52.setText("- Juguete Coffee Monster");
        menu.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 200, -1));

        jLabel53.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel53.setText("3. Cookies de Chocolate");
        menu.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 200, -1));

        jLabel54.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel54.setText("5. Nuevo Menú Celíaco");
        menu.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 200, -1));

        jLabel56.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel56.setText("4. Macedonia de Frutas");
        menu.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 200, -1));

        BackGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\Carta\\FondoCartaMarronDefinitivo.jpg")); // NOI18N
        menu.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contrasenaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaBoxActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void menuCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCartaActionPerformed

    private void atrasIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasIconMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_atrasIconMouseClicked

    private void atrasTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTextMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_atrasTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel atrasIcon;
    private javax.swing.JLabel atrasText;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel cartaDulceText;
    private javax.swing.JLabel cartaSaladaText;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel contrasaenaText;
    private javax.swing.JPasswordField contrasenaBox;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel fineLine1;
    private javax.swing.JLabel fineLine2;
    private javax.swing.JLabel fineLine3;
    private javax.swing.JLabel fineLine4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField menuCarta;
    private javax.swing.JLabel menuDesp;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel producto1;
    private javax.swing.JLabel producto2;
    private javax.swing.JLabel producto3;
    private javax.swing.JLabel producto4;
    private javax.swing.JLabel producto5;
    private javax.swing.JLabel producto6;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel underlineProducto6;
    private javax.swing.JLabel usuarioText;
    private javax.swing.JScrollPane usuarioTextBox;
    private javax.swing.JTextPane usuarioTextPanel;
    // End of variables declaration//GEN-END:variables
}
