package igu;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Horarios extends javax.swing.JFrame {

    /**
     * Creates new form Horarios
     */
    public Horarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        menuDesp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioText = new javax.swing.JLabel();
        usuarioTextBox = new javax.swing.JScrollPane();
        usuarioTextPanel = new javax.swing.JTextPane();
        separador1 = new javax.swing.JSeparator();
        contrasenaText = new javax.swing.JLabel();
        contrasenaBox = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        enviarButton = new javax.swing.JButton();
        barraSuperior = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        minimizar1 = new javax.swing.JLabel();
        atrasIcon = new javax.swing.JLabel();
        atrasText = new javax.swing.JLabel();
        telefonosTitulo1 = new javax.swing.JTextField();
        menuHorario = new javax.swing.JPanel();
        fechaText = new javax.swing.JTextField();
        fechaComboBox = new javax.swing.JComboBox<>();
        turnoText = new javax.swing.JTextField();
        turnoComboBox = new javax.swing.JComboBox<>();
        camareros = new javax.swing.JPanel();
        persona1 = new javax.swing.JLabel();
        persona2 = new javax.swing.JLabel();
        persona3 = new javax.swing.JLabel();
        persona4 = new javax.swing.JLabel();
        persona5 = new javax.swing.JLabel();
        camarerosText = new javax.swing.JLabel();
        camarerosIcon = new javax.swing.JLabel();
        cocina = new javax.swing.JPanel();
        persona6 = new javax.swing.JLabel();
        persona7 = new javax.swing.JLabel();
        persona8 = new javax.swing.JLabel();
        cocinaText = new javax.swing.JLabel();
        cocinaIcon = new javax.swing.JLabel();
        coordinacion = new javax.swing.JPanel();
        coordinacionText = new javax.swing.JLabel();
        jefedecocinaText = new javax.swing.JLabel();
        persona9 = new javax.swing.JLabel();
        jefedesalaText = new javax.swing.JLabel();
        persona10 = new javax.swing.JLabel();
        coordinacionIcon = new javax.swing.JLabel();
        horario = new javax.swing.JPanel();
        horariosText = new javax.swing.JLabel();
        turnoDeMananaText = new javax.swing.JLabel();
        turnoDeTardeText = new javax.swing.JLabel();
        horarioMananaText = new javax.swing.JLabel();
        horarioTardeText = new javax.swing.JLabel();
        horariosIcon = new javax.swing.JLabel();
        configuracionIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        login.add(menuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        login.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        usuarioText.setBackground(new java.awt.Color(102, 51, 0));
        usuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(120, 77, 60));
        usuarioText.setText("Usuario:");
        usuarioText.setAlignmentX(20.0F);
        login.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        usuarioTextBox.setBorder(null);

        usuarioTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        usuarioTextPanel.setBorder(null);
        usuarioTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        usuarioTextPanel.setText("Ingrese su usuario o email");
        usuarioTextPanel.setAlignmentX(20.0F);
        usuarioTextBox.setViewportView(usuarioTextPanel);

        login.add(usuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        separador1.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        contrasenaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        contrasenaText.setForeground(new java.awt.Color(120, 77, 60));
        contrasenaText.setText("Contraseña:");
        contrasenaText.setAlignmentX(20.0F);
        login.add(contrasenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        contrasenaBox.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaBox.setText("jPasswordField1");
        contrasenaBox.setAlignmentX(20.0F);
        contrasenaBox.setBorder(null);
        contrasenaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaBoxActionPerformed(evt);
            }
        });
        login.add(contrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        enviarButton.setBackground(new java.awt.Color(120, 77, 60));
        enviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Enviar");
        enviarButton.setAlignmentX(20.0F);
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        login.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        barraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        barraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        barraSuperior.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        minimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        barraSuperior.add(minimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        atrasIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\retroceder.png")); // NOI18N
        atrasIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasIconMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        atrasText.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        atrasText.setForeground(new java.awt.Color(102, 102, 102));
        atrasText.setText("ATRÁS");
        atrasText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasTextMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        telefonosTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        telefonosTitulo1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        telefonosTitulo1.setForeground(new java.awt.Color(120, 77, 60));
        telefonosTitulo1.setText("HORARIOS");
        telefonosTitulo1.setBorder(null);
        telefonosTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonosTitulo1ActionPerformed(evt);
            }
        });
        barraSuperior.add(telefonosTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        getContentPane().add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        menuHorario.setBackground(new java.awt.Color(255, 255, 255));
        menuHorario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaText.setBackground(new java.awt.Color(255, 255, 255));
        fechaText.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        fechaText.setForeground(new java.awt.Color(120, 77, 60));
        fechaText.setText("Fecha:");
        fechaText.setBorder(null);
        fechaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTextActionPerformed(evt);
            }
        });
        menuHorario.add(fechaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        fechaComboBox.setBackground(new java.awt.Color(120, 77, 60));
        fechaComboBox.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        fechaComboBox.setForeground(new java.awt.Color(255, 255, 255));
        fechaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primera Semana", "Segunda Semana", "Tercera Semana", "Cuarta Semana" }));
        fechaComboBox.setBorder(null);
        fechaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaComboBoxActionPerformed(evt);
            }
        });
        menuHorario.add(fechaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 170, 40));

        turnoText.setBackground(new java.awt.Color(255, 255, 255));
        turnoText.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        turnoText.setForeground(new java.awt.Color(120, 77, 60));
        turnoText.setText("Turno:");
        turnoText.setBorder(null);
        turnoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoTextActionPerformed(evt);
            }
        });
        menuHorario.add(turnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 40));

        turnoComboBox.setBackground(new java.awt.Color(120, 77, 60));
        turnoComboBox.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        turnoComboBox.setForeground(new java.awt.Color(255, 255, 255));
        turnoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Noche" }));
        turnoComboBox.setBorder(null);
        turnoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoComboBoxActionPerformed(evt);
            }
        });
        menuHorario.add(turnoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 160, 40));

        camareros.setBackground(new java.awt.Color(120, 77, 60));
        camareros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        persona1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona1.setForeground(new java.awt.Color(255, 255, 255));
        persona1.setText("Pedro Campos");
        camareros.add(persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        persona2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona2.setForeground(new java.awt.Color(255, 255, 255));
        persona2.setText("Laura Carvajal");
        camareros.add(persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        persona3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona3.setForeground(new java.awt.Color(255, 255, 255));
        persona3.setText("Iñigo Dominguez");
        camareros.add(persona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        persona4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona4.setForeground(new java.awt.Color(255, 255, 255));
        persona4.setText("Susana Pérez");
        camareros.add(persona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        persona5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona5.setForeground(new java.awt.Color(255, 255, 255));
        persona5.setText("Raúl Montosa");
        camareros.add(persona5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        camarerosText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        camarerosText.setForeground(new java.awt.Color(255, 255, 255));
        camarerosText.setText("CAMAREROS");
        camareros.add(camarerosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        camarerosIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\camarero.png")); // NOI18N
        camareros.add(camarerosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        menuHorario.add(camareros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 250));

        cocina.setBackground(new java.awt.Color(120, 77, 60));
        cocina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        persona6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona6.setForeground(new java.awt.Color(255, 255, 255));
        persona6.setText("Elena Gutiérrez");
        cocina.add(persona6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        persona7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona7.setForeground(new java.awt.Color(255, 255, 255));
        persona7.setText("Óscar Delgado");
        cocina.add(persona7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        persona8.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona8.setForeground(new java.awt.Color(255, 255, 255));
        persona8.setText("Emilio Castellano");
        cocina.add(persona8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cocinaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        cocinaText.setForeground(new java.awt.Color(255, 255, 255));
        cocinaText.setText("COCINA");
        cocina.add(cocinaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, -1));

        cocinaIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\cocinero.png")); // NOI18N
        cocina.add(cocinaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        menuHorario.add(cocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, 250));

        coordinacion.setBackground(new java.awt.Color(120, 77, 60));
        coordinacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coordinacionText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        coordinacionText.setForeground(new java.awt.Color(255, 255, 255));
        coordinacionText.setText("COORDINACIÓN");
        coordinacion.add(coordinacionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jefedecocinaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jefedecocinaText.setForeground(new java.awt.Color(255, 255, 255));
        jefedecocinaText.setText("Jefe de Cocina:");
        coordinacion.add(jefedecocinaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        persona9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona9.setForeground(new java.awt.Color(255, 255, 255));
        persona9.setText("Sofía Herrero");
        coordinacion.add(persona9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jefedesalaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jefedesalaText.setForeground(new java.awt.Color(255, 255, 255));
        jefedesalaText.setText("Jefe de Sala:");
        coordinacion.add(jefedesalaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        persona10.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        persona10.setForeground(new java.awt.Color(255, 255, 255));
        persona10.setText("Luís Carvajal");
        coordinacion.add(persona10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        coordinacionIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\jefe.png")); // NOI18N
        coordinacion.add(coordinacionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, -1));

        menuHorario.add(coordinacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 230, 250));

        horario.setBackground(new java.awt.Color(120, 77, 60));
        horario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horariosText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        horariosText.setForeground(new java.awt.Color(255, 255, 255));
        horariosText.setText("HORARIOS");
        horario.add(horariosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        turnoDeMananaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        turnoDeMananaText.setForeground(new java.awt.Color(255, 255, 255));
        turnoDeMananaText.setText("Turno de Mañana");
        horario.add(turnoDeMananaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        turnoDeTardeText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        turnoDeTardeText.setForeground(new java.awt.Color(255, 255, 255));
        turnoDeTardeText.setText("Turno de Tarde");
        horario.add(turnoDeTardeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        horarioMananaText.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        horarioMananaText.setForeground(new java.awt.Color(255, 255, 255));
        horarioMananaText.setText("L-V de 06:00 a 14:00");
        horario.add(horarioMananaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        horarioTardeText.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        horarioTardeText.setForeground(new java.awt.Color(255, 255, 255));
        horarioTardeText.setText("L-V de 14:00 a 22:00 ");
        horario.add(horarioTardeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        horariosIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\reloj.png")); // NOI18N
        horario.add(horariosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        menuHorario.add(horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 500, 130));

        configuracionIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\Reservas\\configuraciones.png")); // NOI18N
        menuHorario.add(configuracionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        getContentPane().add(menuHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contrasenaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaBoxActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void turnoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turnoComboBoxActionPerformed

    private void fechaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaComboBoxActionPerformed

    private void telefonosTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonosTitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonosTitulo1ActionPerformed

    private void turnoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turnoTextActionPerformed

    private void fechaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTextActionPerformed

    private void atrasIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasIconMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_atrasIconMouseClicked

    private void atrasTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTextMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_atrasTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atrasIcon;
    private javax.swing.JLabel atrasText;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JPanel camareros;
    private javax.swing.JLabel camarerosIcon;
    private javax.swing.JLabel camarerosText;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPanel cocina;
    private javax.swing.JLabel cocinaIcon;
    private javax.swing.JLabel cocinaText;
    private javax.swing.JLabel configuracionIcon;
    private javax.swing.JPasswordField contrasenaBox;
    private javax.swing.JLabel contrasenaText;
    private javax.swing.JPanel coordinacion;
    private javax.swing.JLabel coordinacionIcon;
    private javax.swing.JLabel coordinacionText;
    private javax.swing.JButton enviarButton;
    private javax.swing.JComboBox<String> fechaComboBox;
    private javax.swing.JTextField fechaText;
    private javax.swing.JPanel horario;
    private javax.swing.JLabel horarioMananaText;
    private javax.swing.JLabel horarioTardeText;
    private javax.swing.JLabel horariosIcon;
    private javax.swing.JLabel horariosText;
    private javax.swing.JLabel jefedecocinaText;
    private javax.swing.JLabel jefedesalaText;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuDesp;
    private javax.swing.JPanel menuHorario;
    private javax.swing.JLabel minimizar1;
    private javax.swing.JLabel persona1;
    private javax.swing.JLabel persona10;
    private javax.swing.JLabel persona2;
    private javax.swing.JLabel persona3;
    private javax.swing.JLabel persona4;
    private javax.swing.JLabel persona5;
    private javax.swing.JLabel persona6;
    private javax.swing.JLabel persona7;
    private javax.swing.JLabel persona8;
    private javax.swing.JLabel persona9;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField telefonosTitulo1;
    private javax.swing.JComboBox<String> turnoComboBox;
    private javax.swing.JLabel turnoDeMananaText;
    private javax.swing.JLabel turnoDeTardeText;
    private javax.swing.JTextField turnoText;
    private javax.swing.JLabel usuarioText;
    private javax.swing.JScrollPane usuarioTextBox;
    private javax.swing.JTextPane usuarioTextPanel;
    // End of variables declaration//GEN-END:variables
}
