package igu;

import java.awt.Color;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        menuDesp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioText = new javax.swing.JLabel();
        usuarioTextBox = new javax.swing.JScrollPane();
        usuarioTextPanel = new javax.swing.JTextPane();
        separador1 = new javax.swing.JSeparator();
        contrasaenaText = new javax.swing.JLabel();
        contrasenaBox = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        enviarButton = new javax.swing.JButton();
        barraSuperior = new javax.swing.JPanel();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        iconoCafe = new javax.swing.JLabel();
        iconoTelf = new javax.swing.JLabel();
        iconoOpen = new javax.swing.JLabel();
        iconoCalendar = new javax.swing.JLabel();
        iconoMenu = new javax.swing.JLabel();
        iconoReserv = new javax.swing.JLabel();
        sucursalesTexto = new javax.swing.JLabel();
        telefonoTexto = new javax.swing.JLabel();
        horariosTexto = new javax.swing.JLabel();
        eventosTexto = new javax.swing.JLabel();
        cartaTexto = new javax.swing.JLabel();
        reservasTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        login.add(menuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        login.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        usuarioText.setBackground(new java.awt.Color(102, 51, 0));
        usuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(120, 77, 60));
        usuarioText.setText("Usuario:");
        usuarioText.setAlignmentX(20.0F);
        login.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        usuarioTextBox.setBorder(null);

        usuarioTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        usuarioTextPanel.setBorder(null);
        usuarioTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        usuarioTextPanel.setText("Ingrese su usuario o email");
        usuarioTextPanel.setAlignmentX(20.0F);
        usuarioTextBox.setViewportView(usuarioTextPanel);

        login.add(usuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        separador1.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        contrasaenaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        contrasaenaText.setForeground(new java.awt.Color(120, 77, 60));
        contrasaenaText.setText("Contraseña:");
        contrasaenaText.setAlignmentX(20.0F);
        login.add(contrasaenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        contrasenaBox.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaBox.setText("jPasswordField1");
        contrasenaBox.setAlignmentX(20.0F);
        contrasenaBox.setBorder(null);
        contrasenaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaBoxActionPerformed(evt);
            }
        });
        login.add(contrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        enviarButton.setBackground(new java.awt.Color(120, 77, 60));
        enviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Enviar");
        enviarButton.setAlignmentX(20.0F);
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        login.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        barraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        barraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        barraSuperior.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        barraSuperior.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        getContentPane().add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/Sucursales.png"))); // NOI18N
        iconoCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoCafeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconoCafeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconoCafeMouseExited(evt);
            }
        });
        menu.add(iconoCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        iconoTelf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/llamada-telefonica.png"))); // NOI18N
        iconoTelf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoTelfMouseClicked(evt);
            }
        });
        menu.add(iconoTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        iconoOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/abierto.png"))); // NOI18N
        iconoOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoOpenMouseClicked(evt);
            }
        });
        menu.add(iconoOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        iconoCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/evento.png"))); // NOI18N
        iconoCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoCalendarMouseClicked(evt);
            }
        });
        menu.add(iconoCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        iconoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menu.png"))); // NOI18N
        iconoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoMenuMouseClicked(evt);
            }
        });
        menu.add(iconoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        iconoReserv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/reservado.png"))); // NOI18N
        iconoReserv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoReservMouseClicked(evt);
            }
        });
        menu.add(iconoReserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        sucursalesTexto.setBackground(new java.awt.Color(102, 102, 102));
        sucursalesTexto.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        sucursalesTexto.setForeground(new java.awt.Color(102, 102, 102));
        sucursalesTexto.setText("SUCURSALES");
        sucursalesTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sucursalesTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sucursalesTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sucursalesTextoMouseExited(evt);
            }
        });
        menu.add(sucursalesTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 225, -1, -1));

        telefonoTexto.setBackground(new java.awt.Color(102, 102, 102));
        telefonoTexto.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        telefonoTexto.setForeground(new java.awt.Color(102, 102, 102));
        telefonoTexto.setText("TELÉFONOS");
        telefonoTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoTextoMouseClicked(evt);
            }
        });
        menu.add(telefonoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 225, -1, -1));

        horariosTexto.setBackground(new java.awt.Color(102, 102, 102));
        horariosTexto.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        horariosTexto.setForeground(new java.awt.Color(102, 102, 102));
        horariosTexto.setText("HORARIOS");
        horariosTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                horariosTextoMouseClicked(evt);
            }
        });
        menu.add(horariosTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 225, -1, -1));

        eventosTexto.setBackground(new java.awt.Color(102, 102, 102));
        eventosTexto.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        eventosTexto.setForeground(new java.awt.Color(102, 102, 102));
        eventosTexto.setText("EVENTOS");
        eventosTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventosTextoMouseClicked(evt);
            }
        });
        menu.add(eventosTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        cartaTexto.setBackground(new java.awt.Color(102, 102, 102));
        cartaTexto.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        cartaTexto.setForeground(new java.awt.Color(102, 102, 102));
        cartaTexto.setText("CARTA");
        cartaTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaTextoMouseClicked(evt);
            }
        });
        menu.add(cartaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 440, -1, -1));

        reservasTexto.setBackground(new java.awt.Color(102, 102, 102));
        reservasTexto.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        reservasTexto.setForeground(new java.awt.Color(102, 102, 102));
        reservasTexto.setText("RESERVAS");
        reservasTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasTextoMouseClicked(evt);
            }
        });
        menu.add(reservasTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 440, -1, -1));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void contrasenaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaBoxActionPerformed

    private void iconoCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCafeMouseClicked
        Sucursales abrir = new Sucursales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_iconoCafeMouseClicked

    private void sucursalesTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sucursalesTextoMouseClicked
        Sucursales abrir = new Sucursales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_sucursalesTextoMouseClicked

    private void iconoTelfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoTelfMouseClicked
        Telefonos abrir = new Telefonos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_iconoTelfMouseClicked

    private void telefonoTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoTextoMouseClicked
        Telefonos abrir = new Telefonos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextoMouseClicked

    private void iconoOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoOpenMouseClicked
        Horarios abrir = new Horarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_iconoOpenMouseClicked

    private void horariosTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horariosTextoMouseClicked
        Horarios abrir = new Horarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_horariosTextoMouseClicked

    private void iconoCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCalendarMouseClicked
        Eventos abrir = new Eventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_iconoCalendarMouseClicked

    private void eventosTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventosTextoMouseClicked
        Eventos abrir = new Eventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_eventosTextoMouseClicked

    private void iconoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoMenuMouseClicked
        Carta abrir = new Carta();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_iconoMenuMouseClicked

    private void cartaTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaTextoMouseClicked
        Carta abrir = new Carta();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_cartaTextoMouseClicked

    private void iconoReservMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoReservMouseClicked
        Eventos abrir = new Eventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_iconoReservMouseClicked

    private void reservasTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasTextoMouseClicked
        Eventos abrir = new Eventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_reservasTextoMouseClicked

    private void iconoCafeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCafeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoCafeMouseExited

    private void iconoCafeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCafeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoCafeMouseEntered

    private void sucursalesTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sucursalesTextoMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_sucursalesTextoMouseEntered

    private void sucursalesTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sucursalesTextoMouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_sucursalesTextoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel cartaTexto;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel contrasaenaText;
    private javax.swing.JPasswordField contrasenaBox;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel eventosTexto;
    private javax.swing.JLabel horariosTexto;
    private javax.swing.JLabel iconoCafe;
    private javax.swing.JLabel iconoCalendar;
    private javax.swing.JLabel iconoMenu;
    private javax.swing.JLabel iconoOpen;
    private javax.swing.JLabel iconoReserv;
    private javax.swing.JLabel iconoTelf;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuDesp;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel reservasTexto;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel sucursalesTexto;
    private javax.swing.JLabel telefonoTexto;
    private javax.swing.JLabel usuarioText;
    private javax.swing.JScrollPane usuarioTextBox;
    private javax.swing.JTextPane usuarioTextPanel;
    // End of variables declaration//GEN-END:variables
}
