package igu;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class NewClientPopUp extends javax.swing.JFrame {

    /**
     * Creates new form NewClientPopUp
     */
    public NewClientPopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUpNC = new javax.swing.JPanel();
        UserIcon = new javax.swing.JLabel();
        UsuarioNameText = new javax.swing.JLabel();
        UsuarioTextBox = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Separador1 = new javax.swing.JSeparator();
        UsuarioApellText = new javax.swing.JLabel();
        UsuarioTextBox1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        Separador2 = new javax.swing.JSeparator();
        UsuarioTelfText = new javax.swing.JLabel();
        UsuarioTextBox2 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        SeparadorBusqCliente3 = new javax.swing.JSeparator();
        UsuarioCPText = new javax.swing.JLabel();
        UsuarioTextBox3 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        SeparadorBusqCliente4 = new javax.swing.JSeparator();
        UsuarioIDText = new javax.swing.JLabel();
        UsuarioTextBox5 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        SeparadorBusqCliente = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        RegistrarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PopUpNC.setBackground(new java.awt.Color(255, 255, 255));
        PopUpNC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/usuario (1).png"))); // NOI18N
        PopUpNC.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        UsuarioNameText.setBackground(new java.awt.Color(102, 51, 0));
        UsuarioNameText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UsuarioNameText.setForeground(new java.awt.Color(120, 77, 60));
        UsuarioNameText.setText("Nombre:");
        UsuarioNameText.setAlignmentX(20.0F);
        PopUpNC.add(UsuarioNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        UsuarioTextBox.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane1.setText("Ingrese nombre del cliente");
        jTextPane1.setAlignmentX(20.0F);
        UsuarioTextBox.setViewportView(jTextPane1);

        PopUpNC.add(UsuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 20));

        Separador1.setForeground(new java.awt.Color(204, 204, 204));
        PopUpNC.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 10));

        UsuarioApellText.setBackground(new java.awt.Color(102, 51, 0));
        UsuarioApellText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UsuarioApellText.setForeground(new java.awt.Color(120, 77, 60));
        UsuarioApellText.setText("Apellidos:");
        UsuarioApellText.setAlignmentX(20.0F);
        PopUpNC.add(UsuarioApellText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        UsuarioTextBox1.setBorder(null);

        jTextPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane2.setBorder(null);
        jTextPane2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane2.setText("Ingrese apellidos del cliente");
        jTextPane2.setAlignmentX(20.0F);
        UsuarioTextBox1.setViewportView(jTextPane2);

        PopUpNC.add(UsuarioTextBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 20));

        Separador2.setForeground(new java.awt.Color(204, 204, 204));
        PopUpNC.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 290, 10));

        UsuarioTelfText.setBackground(new java.awt.Color(102, 51, 0));
        UsuarioTelfText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UsuarioTelfText.setForeground(new java.awt.Color(120, 77, 60));
        UsuarioTelfText.setText("Teléfono:");
        UsuarioTelfText.setAlignmentX(20.0F);
        PopUpNC.add(UsuarioTelfText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        UsuarioTextBox2.setBorder(null);

        jTextPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane3.setBorder(null);
        jTextPane3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane3.setText("Ingrese  contacto telefónico");
        jTextPane3.setAlignmentX(20.0F);
        UsuarioTextBox2.setViewportView(jTextPane3);

        PopUpNC.add(UsuarioTextBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 230, 20));

        SeparadorBusqCliente3.setForeground(new java.awt.Color(204, 204, 204));
        PopUpNC.add(SeparadorBusqCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 290, 10));

        UsuarioCPText.setBackground(new java.awt.Color(102, 51, 0));
        UsuarioCPText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UsuarioCPText.setForeground(new java.awt.Color(120, 77, 60));
        UsuarioCPText.setText("CP:");
        UsuarioCPText.setAlignmentX(20.0F);
        PopUpNC.add(UsuarioCPText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        UsuarioTextBox3.setBorder(null);

        jTextPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane4.setBorder(null);
        jTextPane4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane4.setText("Ingrese Código Postal");
        jTextPane4.setAlignmentX(20.0F);
        UsuarioTextBox3.setViewportView(jTextPane4);

        PopUpNC.add(UsuarioTextBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 230, 20));

        SeparadorBusqCliente4.setForeground(new java.awt.Color(204, 204, 204));
        PopUpNC.add(SeparadorBusqCliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 290, 10));

        UsuarioIDText.setBackground(new java.awt.Color(102, 51, 0));
        UsuarioIDText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UsuarioIDText.setForeground(new java.awt.Color(120, 77, 60));
        UsuarioIDText.setText("ID Cliente:");
        UsuarioIDText.setAlignmentX(20.0F);
        PopUpNC.add(UsuarioIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        UsuarioTextBox5.setBorder(null);

        jTextPane6.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane6.setBorder(null);
        jTextPane6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane6.setText("Ingrese ID del cliente");
        jTextPane6.setAlignmentX(20.0F);
        UsuarioTextBox5.setViewportView(jTextPane6);

        PopUpNC.add(UsuarioTextBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 20));

        SeparadorBusqCliente.setForeground(new java.awt.Color(204, 204, 204));
        PopUpNC.add(SeparadorBusqCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 290, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        PopUpNC.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        RegistrarButton.setBackground(new java.awt.Color(120, 77, 60));
        RegistrarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        RegistrarButton.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarButton.setText("Registrar");
        RegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarButtonActionPerformed(evt);
            }
        });
        PopUpNC.add(RegistrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 110, 40));

        CancelarButton.setBackground(new java.awt.Color(120, 77, 60));
        CancelarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelarButton.setText("Cancelar");
        PopUpNC.add(CancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 110, 40));

        getContentPane().add(PopUpNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewClientPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewClientPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewClientPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewClientPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewClientPopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarButton;
    private javax.swing.JPanel PopUpNC;
    private javax.swing.JButton RegistrarButton;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JSeparator SeparadorBusqCliente;
    private javax.swing.JSeparator SeparadorBusqCliente3;
    private javax.swing.JSeparator SeparadorBusqCliente4;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UsuarioApellText;
    private javax.swing.JLabel UsuarioCPText;
    private javax.swing.JLabel UsuarioIDText;
    private javax.swing.JLabel UsuarioNameText;
    private javax.swing.JLabel UsuarioTelfText;
    private javax.swing.JScrollPane UsuarioTextBox;
    private javax.swing.JScrollPane UsuarioTextBox1;
    private javax.swing.JScrollPane UsuarioTextBox2;
    private javax.swing.JScrollPane UsuarioTextBox3;
    private javax.swing.JScrollPane UsuarioTextBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane6;
    // End of variables declaration//GEN-END:variables
}
