package igu;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Reservas extends javax.swing.JFrame {

    /**
     * Creates new form Reservas
     */
    public Reservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        menuDesp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioText = new javax.swing.JLabel();
        usuarioTextBox = new javax.swing.JScrollPane();
        usuarioTextPanel = new javax.swing.JTextPane();
        separador1 = new javax.swing.JSeparator();
        contrasaenaText = new javax.swing.JLabel();
        contrasenaBox = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        enviarButton = new javax.swing.JButton();
        barraSuperior = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        minimizar1 = new javax.swing.JLabel();
        atrasIcon = new javax.swing.JLabel();
        atrasText = new javax.swing.JLabel();
        reservasText = new javax.swing.JTextField();
        menu = new javax.swing.JPanel();
        hacerReserva = new javax.swing.JPanel();
        hacerReserva1 = new javax.swing.JPanel();
        hacerReservaIcon = new javax.swing.JLabel();
        idCliente = new javax.swing.JLabel();
        idClienteTextBox = new javax.swing.JScrollPane();
        idTextPanel = new javax.swing.JTextPane();
        separadorID = new javax.swing.JSeparator();
        nombre = new javax.swing.JLabel();
        nombreTextBox = new javax.swing.JScrollPane();
        nombreTextPanel = new javax.swing.JTextPane();
        separadorNombre = new javax.swing.JSeparator();
        asistencias = new javax.swing.JLabel();
        asistenciasTextBox = new javax.swing.JScrollPane();
        asistenciasTextPanel = new javax.swing.JTextPane();
        separadorAsistencias = new javax.swing.JSeparator();
        telefono = new javax.swing.JLabel();
        telefonoTextBox = new javax.swing.JScrollPane();
        telefonoTextPanel = new javax.swing.JTextPane();
        separadorTelefono = new javax.swing.JSeparator();
        horaDeReserva = new javax.swing.JLabel();
        reservaTextBox = new javax.swing.JScrollPane();
        reservaTextPanel = new javax.swing.JTextPane();
        separadorReserva = new javax.swing.JSeparator();
        generarReservaButton = new javax.swing.JButton();
        reservaActiva = new javax.swing.JPanel();
        busquedaReservas = new javax.swing.JPanel();
        busquedaReservasIcon = new javax.swing.JLabel();
        nombreText = new javax.swing.JLabel();
        nombreTextBox2 = new javax.swing.JScrollPane();
        nombreTextPanel2 = new javax.swing.JTextPane();
        separadorNombre2 = new javax.swing.JSeparator();
        idClienteText = new javax.swing.JLabel();
        idClienteTextBox2 = new javax.swing.JScrollPane();
        idClienteTextPanel2 = new javax.swing.JTextPane();
        separadorIdCliente2 = new javax.swing.JSeparator();
        consultarReservaButton = new javax.swing.JButton();
        modificarReservas = new javax.swing.JPanel();
        modificarReservaIcon = new javax.swing.JLabel();
        modificarReservaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        login.add(menuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        login.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        usuarioText.setBackground(new java.awt.Color(102, 51, 0));
        usuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(120, 77, 60));
        usuarioText.setText("Usuario:");
        usuarioText.setAlignmentX(20.0F);
        login.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        usuarioTextBox.setBorder(null);

        usuarioTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        usuarioTextPanel.setBorder(null);
        usuarioTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        usuarioTextPanel.setText("Ingrese su usuario o email");
        usuarioTextPanel.setAlignmentX(20.0F);
        usuarioTextBox.setViewportView(usuarioTextPanel);

        login.add(usuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        separador1.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        contrasaenaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        contrasaenaText.setForeground(new java.awt.Color(120, 77, 60));
        contrasaenaText.setText("Contraseña:");
        contrasaenaText.setAlignmentX(20.0F);
        login.add(contrasaenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        contrasenaBox.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaBox.setText("jPasswordField1");
        contrasenaBox.setAlignmentX(20.0F);
        contrasenaBox.setBorder(null);
        contrasenaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaBoxActionPerformed(evt);
            }
        });
        login.add(contrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        enviarButton.setBackground(new java.awt.Color(120, 77, 60));
        enviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Enviar");
        enviarButton.setAlignmentX(20.0F);
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        login.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        barraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        barraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        barraSuperior.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        minimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        barraSuperior.add(minimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        atrasIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\retroceder.png")); // NOI18N
        atrasIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasIconMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        atrasText.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        atrasText.setForeground(new java.awt.Color(102, 102, 102));
        atrasText.setText("ATRÁS");
        atrasText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasTextMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        reservasText.setBackground(new java.awt.Color(255, 255, 255));
        reservasText.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        reservasText.setForeground(new java.awt.Color(120, 77, 60));
        reservasText.setText("RESERVAS");
        reservasText.setBorder(null);
        reservasText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasTextActionPerformed(evt);
            }
        });
        barraSuperior.add(reservasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        getContentPane().add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hacerReserva.setBackground(new java.awt.Color(120, 77, 60));
        hacerReserva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hacerReserva.setForeground(new java.awt.Color(120, 77, 60));
        hacerReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hacerReserva1.setBackground(new java.awt.Color(255, 255, 255));
        hacerReserva1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hacerReservaIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\Reservas\\calendario3.png")); // NOI18N
        hacerReserva1.add(hacerReservaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        idCliente.setBackground(new java.awt.Color(102, 51, 0));
        idCliente.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        idCliente.setForeground(new java.awt.Color(120, 77, 60));
        idCliente.setText("ID Cliente:");
        idCliente.setAlignmentX(20.0F);
        hacerReserva1.add(idCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        idClienteTextBox.setBorder(null);

        idTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        idTextPanel.setBorder(null);
        idTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        idTextPanel.setText("Ingrese identificador del cliente");
        idTextPanel.setAlignmentX(20.0F);
        idClienteTextBox.setViewportView(idTextPanel);

        hacerReserva1.add(idClienteTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, 20));

        separadorID.setForeground(new java.awt.Color(204, 204, 204));
        hacerReserva1.add(separadorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 10));

        nombre.setBackground(new java.awt.Color(102, 51, 0));
        nombre.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(120, 77, 60));
        nombre.setText("Nombre:");
        nombre.setAlignmentX(20.0F);
        hacerReserva1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        nombreTextBox.setBorder(null);

        nombreTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        nombreTextPanel.setBorder(null);
        nombreTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        nombreTextPanel.setText("Ingrese nombre del cliente");
        nombreTextPanel.setAlignmentX(20.0F);
        nombreTextBox.setViewportView(nombreTextPanel);

        hacerReserva1.add(nombreTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 20));

        separadorNombre.setForeground(new java.awt.Color(204, 204, 204));
        hacerReserva1.add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 270, 10));

        asistencias.setBackground(new java.awt.Color(102, 51, 0));
        asistencias.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        asistencias.setForeground(new java.awt.Color(120, 77, 60));
        asistencias.setText("Asistencias:");
        asistencias.setAlignmentX(20.0F);
        hacerReserva1.add(asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        asistenciasTextBox.setBorder(null);

        asistenciasTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        asistenciasTextPanel.setBorder(null);
        asistenciasTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        asistenciasTextPanel.setText("Ingrese número de personas");
        asistenciasTextPanel.setAlignmentX(20.0F);
        asistenciasTextBox.setViewportView(asistenciasTextPanel);

        hacerReserva1.add(asistenciasTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 20));

        separadorAsistencias.setForeground(new java.awt.Color(204, 204, 204));
        hacerReserva1.add(separadorAsistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 270, 10));

        telefono.setBackground(new java.awt.Color(102, 51, 0));
        telefono.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        telefono.setForeground(new java.awt.Color(120, 77, 60));
        telefono.setText("Teléfono:");
        telefono.setAlignmentX(20.0F);
        hacerReserva1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        telefonoTextBox.setBorder(null);

        telefonoTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        telefonoTextPanel.setBorder(null);
        telefonoTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        telefonoTextPanel.setText("Ingrese  contacto telefónico");
        telefonoTextPanel.setAlignmentX(20.0F);
        telefonoTextBox.setViewportView(telefonoTextPanel);

        hacerReserva1.add(telefonoTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 230, 20));

        separadorTelefono.setForeground(new java.awt.Color(204, 204, 204));
        hacerReserva1.add(separadorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 270, 10));

        horaDeReserva.setBackground(new java.awt.Color(102, 51, 0));
        horaDeReserva.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        horaDeReserva.setForeground(new java.awt.Color(120, 77, 60));
        horaDeReserva.setText("Hora de Reserva:");
        horaDeReserva.setAlignmentX(20.0F);
        hacerReserva1.add(horaDeReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        reservaTextBox.setBorder(null);

        reservaTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        reservaTextPanel.setBorder(null);
        reservaTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        reservaTextPanel.setText("Ingrese hora de asistencia");
        reservaTextPanel.setAlignmentX(20.0F);
        reservaTextBox.setViewportView(reservaTextPanel);

        hacerReserva1.add(reservaTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 230, 20));

        separadorReserva.setForeground(new java.awt.Color(204, 204, 204));
        hacerReserva1.add(separadorReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 270, 10));

        generarReservaButton.setBackground(new java.awt.Color(120, 77, 60));
        generarReservaButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        generarReservaButton.setForeground(new java.awt.Color(255, 255, 255));
        generarReservaButton.setText("Generar Reserva");
        generarReservaButton.setAlignmentX(20.0F);
        generarReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReservaButtonActionPerformed(evt);
            }
        });
        hacerReserva1.add(generarReservaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 170, 40));

        hacerReserva.add(hacerReserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 480));

        menu.add(hacerReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 500));

        reservaActiva.setBackground(new java.awt.Color(120, 77, 60));
        reservaActiva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reservaActiva.setForeground(new java.awt.Color(120, 77, 60));
        reservaActiva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busquedaReservas.setBackground(new java.awt.Color(255, 255, 255));
        busquedaReservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busquedaReservasIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\Reservas\\buscador.png")); // NOI18N
        busquedaReservas.add(busquedaReservasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        nombreText.setBackground(new java.awt.Color(102, 51, 0));
        nombreText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        nombreText.setForeground(new java.awt.Color(120, 77, 60));
        nombreText.setText("Nombre:");
        nombreText.setAlignmentX(20.0F);
        busquedaReservas.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        nombreTextBox2.setBorder(null);

        nombreTextPanel2.setBackground(new java.awt.Color(255, 255, 255));
        nombreTextPanel2.setBorder(null);
        nombreTextPanel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        nombreTextPanel2.setText("Ingrese nombre del cliente");
        nombreTextPanel2.setAlignmentX(20.0F);
        nombreTextBox2.setViewportView(nombreTextPanel2);

        busquedaReservas.add(nombreTextBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, 20));

        separadorNombre2.setForeground(new java.awt.Color(204, 204, 204));
        busquedaReservas.add(separadorNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 10));

        idClienteText.setBackground(new java.awt.Color(102, 51, 0));
        idClienteText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        idClienteText.setForeground(new java.awt.Color(120, 77, 60));
        idClienteText.setText("ID Cliente:");
        idClienteText.setAlignmentX(20.0F);
        busquedaReservas.add(idClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        idClienteTextBox2.setBorder(null);

        idClienteTextPanel2.setBackground(new java.awt.Color(255, 255, 255));
        idClienteTextPanel2.setBorder(null);
        idClienteTextPanel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        idClienteTextPanel2.setText("Ingrese identificador del cliente");
        idClienteTextPanel2.setAlignmentX(20.0F);
        idClienteTextBox2.setViewportView(idClienteTextPanel2);

        busquedaReservas.add(idClienteTextBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 20));

        separadorIdCliente2.setForeground(new java.awt.Color(204, 204, 204));
        busquedaReservas.add(separadorIdCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 270, 10));

        consultarReservaButton.setBackground(new java.awt.Color(120, 77, 60));
        consultarReservaButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        consultarReservaButton.setForeground(new java.awt.Color(255, 255, 255));
        consultarReservaButton.setText("Consultar Reserva");
        consultarReservaButton.setAlignmentX(20.0F);
        consultarReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarReservaButtonActionPerformed(evt);
            }
        });
        busquedaReservas.add(consultarReservaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 170, 40));

        reservaActiva.add(busquedaReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 300));

        modificarReservas.setBackground(new java.awt.Color(255, 255, 255));
        modificarReservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarReservaIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\Reservas\\configuraciones.png")); // NOI18N
        modificarReservas.add(modificarReservaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        modificarReservaButton.setBackground(new java.awt.Color(120, 77, 60));
        modificarReservaButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        modificarReservaButton.setForeground(new java.awt.Color(255, 255, 255));
        modificarReservaButton.setText("Modificar Reserva");
        modificarReservaButton.setAlignmentX(20.0F);
        modificarReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarReservaButtonActionPerformed(evt);
            }
        });
        modificarReservas.add(modificarReservaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, 40));

        reservaActiva.add(modificarReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 330, 170));

        menu.add(reservaActiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 350, 500));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contrasenaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaBoxActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void reservasTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservasTextActionPerformed

    private void generarReservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReservaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generarReservaButtonActionPerformed

    private void modificarReservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarReservaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarReservaButtonActionPerformed

    private void consultarReservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarReservaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarReservaButtonActionPerformed

    private void atrasIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasIconMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_atrasIconMouseClicked

    private void atrasTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasTextMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_atrasTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asistencias;
    private javax.swing.JScrollPane asistenciasTextBox;
    private javax.swing.JTextPane asistenciasTextPanel;
    private javax.swing.JLabel atrasIcon;
    private javax.swing.JLabel atrasText;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JPanel busquedaReservas;
    private javax.swing.JLabel busquedaReservasIcon;
    private javax.swing.JLabel cerrar;
    private javax.swing.JButton consultarReservaButton;
    private javax.swing.JLabel contrasaenaText;
    private javax.swing.JPasswordField contrasenaBox;
    private javax.swing.JButton enviarButton;
    private javax.swing.JButton generarReservaButton;
    private javax.swing.JPanel hacerReserva;
    private javax.swing.JPanel hacerReserva1;
    private javax.swing.JLabel hacerReservaIcon;
    private javax.swing.JLabel horaDeReserva;
    private javax.swing.JLabel idCliente;
    private javax.swing.JLabel idClienteText;
    private javax.swing.JScrollPane idClienteTextBox;
    private javax.swing.JScrollPane idClienteTextBox2;
    private javax.swing.JTextPane idClienteTextPanel2;
    private javax.swing.JTextPane idTextPanel;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuDesp;
    private javax.swing.JLabel minimizar1;
    private javax.swing.JButton modificarReservaButton;
    private javax.swing.JLabel modificarReservaIcon;
    private javax.swing.JPanel modificarReservas;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreText;
    private javax.swing.JScrollPane nombreTextBox;
    private javax.swing.JScrollPane nombreTextBox2;
    private javax.swing.JTextPane nombreTextPanel;
    private javax.swing.JTextPane nombreTextPanel2;
    private javax.swing.JPanel reservaActiva;
    private javax.swing.JScrollPane reservaTextBox;
    private javax.swing.JTextPane reservaTextPanel;
    private javax.swing.JTextField reservasText;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separadorAsistencias;
    private javax.swing.JSeparator separadorID;
    private javax.swing.JSeparator separadorIdCliente2;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorNombre2;
    private javax.swing.JSeparator separadorReserva;
    private javax.swing.JSeparator separadorTelefono;
    private javax.swing.JLabel telefono;
    private javax.swing.JScrollPane telefonoTextBox;
    private javax.swing.JTextPane telefonoTextPanel;
    private javax.swing.JLabel usuarioText;
    private javax.swing.JScrollPane usuarioTextBox;
    private javax.swing.JTextPane usuarioTextPanel;
    // End of variables declaration//GEN-END:variables
}
