package igu;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Sucursales extends javax.swing.JFrame {

    /**
     * Creates new form Sucursales
     */
    public Sucursales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        menuDesp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioText = new javax.swing.JLabel();
        usuarioTextBox = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        separador1 = new javax.swing.JSeparator();
        contrasenaText = new javax.swing.JLabel();
        contrasenaBox = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        enviarButton = new javax.swing.JButton();
        barraSuperior = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        minimizar1 = new javax.swing.JLabel();
        atrasIcon = new javax.swing.JLabel();
        atrasLabel = new javax.swing.JLabel();
        sucursalesTitulo = new javax.swing.JTextField();
        menuSucursales = new javax.swing.JPanel();
        suc1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        suc1Insta = new javax.swing.JLabel();
        suc1Face = new javax.swing.JLabel();
        suc1Whats = new javax.swing.JLabel();
        qrCode1 = new javax.swing.JLabel();
        suc2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        suc2Insta = new javax.swing.JLabel();
        suc2Face = new javax.swing.JLabel();
        suc2Whats = new javax.swing.JLabel();
        qrCode2 = new javax.swing.JLabel();
        suc3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        suc3Insta = new javax.swing.JLabel();
        suc3Face = new javax.swing.JLabel();
        suc3Whats = new javax.swing.JLabel();
        qrCode3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 575));
        setSize(new java.awt.Dimension(1050, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        login.add(menuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        login.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        usuarioText.setBackground(new java.awt.Color(102, 51, 0));
        usuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(120, 77, 60));
        usuarioText.setText("Usuario:");
        usuarioText.setAlignmentX(20.0F);
        login.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        usuarioTextBox.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane1.setText("Ingrese su usuario o email");
        jTextPane1.setAlignmentX(20.0F);
        usuarioTextBox.setViewportView(jTextPane1);

        login.add(usuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        separador1.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        contrasenaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        contrasenaText.setForeground(new java.awt.Color(120, 77, 60));
        contrasenaText.setText("Contraseña:");
        contrasenaText.setAlignmentX(20.0F);
        login.add(contrasenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        contrasenaBox.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaBox.setText("jPasswordField1");
        contrasenaBox.setAlignmentX(20.0F);
        contrasenaBox.setBorder(null);
        contrasenaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaBoxActionPerformed(evt);
            }
        });
        login.add(contrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        enviarButton.setBackground(new java.awt.Color(120, 77, 60));
        enviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Enviar");
        enviarButton.setAlignmentX(20.0F);
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        login.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        barraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        barraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        barraSuperior.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        minimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        barraSuperior.add(minimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        atrasIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\retroceder.png")); // NOI18N
        atrasIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasIconMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        atrasLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        atrasLabel.setForeground(new java.awt.Color(102, 102, 102));
        atrasLabel.setText("ATRÁS");
        atrasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasLabelMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        sucursalesTitulo.setBackground(new java.awt.Color(255, 255, 255));
        sucursalesTitulo.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        sucursalesTitulo.setForeground(new java.awt.Color(120, 77, 60));
        sucursalesTitulo.setText("SUCURSALES");
        sucursalesTitulo.setBorder(null);
        sucursalesTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalesTituloActionPerformed(evt);
            }
        });
        barraSuperior.add(sucursalesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        menuSucursales.setBackground(new java.awt.Color(255, 255, 255));
        menuSucursales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suc1.setBackground(new java.awt.Color(120, 77, 60));
        suc1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sucursal:");
        suc1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Dirección:");
        suc1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Teléfono:");
        suc1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Horario:");
        suc1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel18.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Código Postal:");
        suc1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Email:");
        suc1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Teatinos");
        suc1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 20));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Avda. la Concepción");
        suc1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 20));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("951 234 567");
        suc1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("8:00- 5:00 , 17:30-22:30 ");
        suc1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("29009");
        suc1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 60, 20));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("m.coffee@coffee.com");
        suc1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        menuSucursales.add(suc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 160));

        suc1Insta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\instagram-(1).jpg")); // NOI18N
        menuSucursales.add(suc1Insta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        suc1Face.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\Facebook-(1).jpg")); // NOI18N
        menuSucursales.add(suc1Face, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        suc1Whats.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\watsap(1).jpg")); // NOI18N
        menuSucursales.add(suc1Whats, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        qrCode1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\QRCafeteria.jpg")); // NOI18N
        menuSucursales.add(qrCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 200));

        suc2.setBackground(new java.awt.Color(120, 77, 60));
        suc2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Sucursal:");
        suc2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Dirección:");
        suc2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Teléfono:");
        suc2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel23.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Horario:");
        suc2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Código Postal:");
        suc2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Email:");
        suc2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("NH Hotel Larios");
        suc2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 20));

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Calle Dos Hermanas");
        suc2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 20));

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("951 567 234");
        suc2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("8:00-15:00 , 17:30-22:30 ");
        suc2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("29109");
        suc2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 20));

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("m.coffee2@coffee.com");
        suc2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        menuSucursales.add(suc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 210, 160));

        suc2Insta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\instagram-(1).jpg")); // NOI18N
        menuSucursales.add(suc2Insta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        suc2Face.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\Facebook-(1).jpg")); // NOI18N
        menuSucursales.add(suc2Face, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        suc2Whats.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\watsap(1).jpg")); // NOI18N
        menuSucursales.add(suc2Whats, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        qrCode2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\QRCafeteria.jpg")); // NOI18N
        menuSucursales.add(qrCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, 200));

        suc3.setBackground(new java.awt.Color(120, 77, 60));
        suc3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Sucursal:");
        suc3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Dirección:");
        suc3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel28.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Teléfono:");
        suc3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel29.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Horario:");
        suc3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel30.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Código Postal:");
        suc3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel31.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Email:");
        suc3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel32.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("Paseo Marítimo");
        suc3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 20));

        jLabel33.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("C. Antonio Banderas");
        suc3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 20));

        jLabel34.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("951 987 123");
        suc3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        jLabel35.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("8:00-15:00 , 17:30-22:30 ");
        suc3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        jLabel36.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("29359");
        suc3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 20));

        jLabel37.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("m.coffee3@coffee.com");
        suc3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        menuSucursales.add(suc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 210, 160));

        suc3Insta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\instagram-(1).jpg")); // NOI18N
        menuSucursales.add(suc3Insta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        suc3Face.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\Facebook-(1).jpg")); // NOI18N
        menuSucursales.add(suc3Face, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        suc3Whats.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\watsap(1).jpg")); // NOI18N
        menuSucursales.add(suc3Whats, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        qrCode3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\SocialMedia\\QRCafeteria.jpg")); // NOI18N
        menuSucursales.add(qrCode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 190, 200));

        getContentPane().add(menuSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contrasenaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaBoxActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void sucursalesTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalesTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucursalesTituloActionPerformed

    private void atrasIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasIconMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_atrasIconMouseClicked

    private void atrasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasLabelMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_atrasLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atrasIcon;
    private javax.swing.JLabel atrasLabel;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPasswordField contrasenaBox;
    private javax.swing.JLabel contrasenaText;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuDesp;
    private javax.swing.JPanel menuSucursales;
    private javax.swing.JLabel minimizar1;
    private javax.swing.JLabel qrCode1;
    private javax.swing.JLabel qrCode2;
    private javax.swing.JLabel qrCode3;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JPanel suc1;
    private javax.swing.JLabel suc1Face;
    private javax.swing.JLabel suc1Insta;
    private javax.swing.JLabel suc1Whats;
    private javax.swing.JPanel suc2;
    private javax.swing.JLabel suc2Face;
    private javax.swing.JLabel suc2Insta;
    private javax.swing.JLabel suc2Whats;
    private javax.swing.JPanel suc3;
    private javax.swing.JLabel suc3Face;
    private javax.swing.JLabel suc3Insta;
    private javax.swing.JLabel suc3Whats;
    private javax.swing.JTextField sucursalesTitulo;
    private javax.swing.JLabel usuarioText;
    private javax.swing.JScrollPane usuarioTextBox;
    // End of variables declaration//GEN-END:variables
}
