package igu;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Telefonos extends javax.swing.JFrame {

    /**
     * Creates new form telefono
     */
    public Telefonos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        menuDesp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioText = new javax.swing.JLabel();
        usuarioTextBox = new javax.swing.JScrollPane();
        usuarioTextPanel = new javax.swing.JTextPane();
        separador1 = new javax.swing.JSeparator();
        contrasaenaText = new javax.swing.JLabel();
        contrasenaBox = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        enviarButton = new javax.swing.JButton();
        barraSuperior = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        minimizar1 = new javax.swing.JLabel();
        atrasIcon = new javax.swing.JLabel();
        atrasLabel = new javax.swing.JLabel();
        telefonosTitulo = new javax.swing.JTextField();
        menuTelefonos = new javax.swing.JPanel();
        busquedaPanel = new javax.swing.JPanel();
        busquedaCliente = new javax.swing.JPanel();
        busqClienText = new javax.swing.JLabel();
        clienteIcon = new javax.swing.JLabel();
        busqClientBox1 = new javax.swing.JScrollPane();
        busqClient1 = new javax.swing.JTextPane();
        separadorBusqCliente = new javax.swing.JSeparator();
        BusquedaButton = new javax.swing.JButton();
        registroCliente = new javax.swing.JPanel();
        RegistroNuevoCliente = new javax.swing.JLabel();
        NewUserSymbol = new javax.swing.JLabel();
        registroPanel1 = new javax.swing.JPanel();
        registroPanel2 = new javax.swing.JPanel();
        registroText = new javax.swing.JLabel();
        listaClientes = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        login.add(menuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        login.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        usuarioText.setBackground(new java.awt.Color(102, 51, 0));
        usuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(120, 77, 60));
        usuarioText.setText("Usuario:");
        usuarioText.setAlignmentX(20.0F);
        login.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        usuarioTextBox.setBorder(null);

        usuarioTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        usuarioTextPanel.setBorder(null);
        usuarioTextPanel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        usuarioTextPanel.setText("Ingrese su usuario o email");
        usuarioTextPanel.setAlignmentX(20.0F);
        usuarioTextBox.setViewportView(usuarioTextPanel);

        login.add(usuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        separador1.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        contrasaenaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        contrasaenaText.setForeground(new java.awt.Color(120, 77, 60));
        contrasaenaText.setText("Contraseña:");
        contrasaenaText.setAlignmentX(20.0F);
        login.add(contrasaenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        contrasenaBox.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaBox.setText("jPasswordField1");
        contrasenaBox.setAlignmentX(20.0F);
        contrasenaBox.setBorder(null);
        contrasenaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaBoxActionPerformed(evt);
            }
        });
        login.add(contrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setForeground(new java.awt.Color(204, 204, 204));
        login.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        enviarButton.setBackground(new java.awt.Color(120, 77, 60));
        enviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Enviar");
        enviarButton.setAlignmentX(20.0F);
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        login.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        barraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        barraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        barraSuperior.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        minimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        barraSuperior.add(minimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        atrasIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\retroceder.png")); // NOI18N
        atrasIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasIconMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        atrasLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        atrasLabel.setForeground(new java.awt.Color(102, 102, 102));
        atrasLabel.setText("ATRÁS");
        atrasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasLabelMouseClicked(evt);
            }
        });
        barraSuperior.add(atrasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        telefonosTitulo.setBackground(new java.awt.Color(255, 255, 255));
        telefonosTitulo.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        telefonosTitulo.setForeground(new java.awt.Color(120, 77, 60));
        telefonosTitulo.setText("TELÉFONOS");
        telefonosTitulo.setBorder(null);
        telefonosTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonosTituloActionPerformed(evt);
            }
        });
        barraSuperior.add(telefonosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        menuTelefonos.setBackground(new java.awt.Color(255, 255, 255));
        menuTelefonos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busquedaPanel.setBackground(new java.awt.Color(120, 77, 60));
        busquedaPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        busquedaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busquedaCliente.setBackground(new java.awt.Color(255, 255, 255));
        busquedaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busqClienText.setBackground(new java.awt.Color(102, 51, 0));
        busqClienText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        busqClienText.setForeground(new java.awt.Color(120, 77, 60));
        busqClienText.setText("Búsqueda de cliente:");
        busqClienText.setAlignmentX(20.0F);
        busquedaCliente.add(busqClienText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        clienteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/usuario (1).png"))); // NOI18N
        busquedaCliente.add(clienteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 130));

        busqClientBox1.setBorder(null);

        busqClient1.setBackground(new java.awt.Color(255, 255, 255));
        busqClient1.setBorder(null);
        busqClient1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        busqClient1.setText("Ingresar Nombre, Apellido, ID o teléfono");
        busqClient1.setAlignmentX(20.0F);
        busqClientBox1.setViewportView(busqClient1);

        busquedaCliente.add(busqClientBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 20));

        separadorBusqCliente.setForeground(new java.awt.Color(204, 204, 204));
        busquedaCliente.add(separadorBusqCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 290, 10));

        BusquedaButton.setBackground(new java.awt.Color(120, 77, 60));
        BusquedaButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        BusquedaButton.setForeground(new java.awt.Color(255, 255, 255));
        BusquedaButton.setText("Buscar");
        BusquedaButton.setAlignmentX(20.0F);
        BusquedaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaButtonActionPerformed(evt);
            }
        });
        busquedaCliente.add(BusquedaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 130, 41));

        busquedaPanel.add(busquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 320));

        registroCliente.setBackground(new java.awt.Color(255, 255, 255));
        registroCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroNuevoCliente.setBackground(new java.awt.Color(102, 51, 0));
        RegistroNuevoCliente.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        RegistroNuevoCliente.setForeground(new java.awt.Color(120, 77, 60));
        RegistroNuevoCliente.setText("Registro de nuevo cliente:");
        RegistroNuevoCliente.setAlignmentX(20.0F);
        registroCliente.add(RegistroNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, -1));

        NewUserSymbol.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\usuarionuevo2.png")); // NOI18N
        registroCliente.add(NewUserSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        busquedaPanel.add(registroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 310, 150));

        menuTelefonos.add(busquedaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 500));

        registroPanel1.setBackground(new java.awt.Color(120, 77, 60));
        registroPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroPanel2.setBackground(new java.awt.Color(255, 255, 255));
        registroPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroText.setBackground(new java.awt.Color(102, 51, 0));
        registroText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        registroText.setForeground(new java.awt.Color(120, 77, 60));
        registroText.setText("Registro de clientes:");
        registroText.setAlignmentX(20.0F);
        registroPanel2.add(registroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        listaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesActionPerformed(evt);
            }
        });
        registroPanel2.add(listaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 410));

        registroPanel1.add(registroPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 480));

        menuTelefonos.add(registroPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 400, 500));

        getContentPane().add(menuTelefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contrasenaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaBoxActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void telefonosTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonosTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonosTituloActionPerformed

    private void BusquedaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaButtonActionPerformed

    private void listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaClientesActionPerformed

    private void atrasIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasIconMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_atrasIconMouseClicked

    private void atrasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasLabelMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_atrasLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telefonos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusquedaButton;
    private javax.swing.JLabel NewUserSymbol;
    private javax.swing.JLabel RegistroNuevoCliente;
    private javax.swing.JLabel atrasIcon;
    private javax.swing.JLabel atrasLabel;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel busqClienText;
    private javax.swing.JTextPane busqClient1;
    private javax.swing.JScrollPane busqClientBox1;
    private javax.swing.JPanel busquedaCliente;
    private javax.swing.JPanel busquedaPanel;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel clienteIcon;
    private javax.swing.JLabel contrasaenaText;
    private javax.swing.JPasswordField contrasenaBox;
    private javax.swing.JButton enviarButton;
    private java.awt.List listaClientes;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuDesp;
    private javax.swing.JPanel menuTelefonos;
    private javax.swing.JLabel minimizar1;
    private javax.swing.JPanel registroCliente;
    private javax.swing.JPanel registroPanel1;
    private javax.swing.JPanel registroPanel2;
    private javax.swing.JLabel registroText;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separadorBusqCliente;
    private javax.swing.JTextField telefonosTitulo;
    private javax.swing.JLabel usuarioText;
    private javax.swing.JScrollPane usuarioTextBox;
    private javax.swing.JTextPane usuarioTextPanel;
    // End of variables declaration//GEN-END:variables
}
