/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Carta extends javax.swing.JFrame {

    /**
     * Creates new form Eventos
     */
    public Carta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        MenuDesp = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JLabel();
        UsuarioTextBox = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Separador1 = new javax.swing.JSeparator();
        ContrasaeñaText = new javax.swing.JLabel();
        ContraseñaBox = new javax.swing.JPasswordField();
        Separador2 = new javax.swing.JSeparator();
        EnviarButton = new javax.swing.JButton();
        BarraSuperior = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        Minimizar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        MenuCarta = new javax.swing.JTextField();
        MENU = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        Login.add(MenuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        Login.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        UsuarioText.setBackground(new java.awt.Color(102, 51, 0));
        UsuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UsuarioText.setForeground(new java.awt.Color(120, 77, 60));
        UsuarioText.setText("Usuario:");
        UsuarioText.setAlignmentX(20.0F);
        Login.add(UsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        UsuarioTextBox.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane1.setText("Ingrese su usuario o email");
        jTextPane1.setAlignmentX(20.0F);
        UsuarioTextBox.setViewportView(jTextPane1);

        Login.add(UsuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        Separador1.setForeground(new java.awt.Color(204, 204, 204));
        Login.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        ContrasaeñaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        ContrasaeñaText.setForeground(new java.awt.Color(120, 77, 60));
        ContrasaeñaText.setText("Contraseña:");
        ContrasaeñaText.setAlignmentX(20.0F);
        Login.add(ContrasaeñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        ContraseñaBox.setBackground(new java.awt.Color(255, 255, 255));
        ContraseñaBox.setText("jPasswordField1");
        ContraseñaBox.setAlignmentX(20.0F);
        ContraseñaBox.setBorder(null);
        ContraseñaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaBoxActionPerformed(evt);
            }
        });
        Login.add(ContraseñaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        Separador2.setBackground(new java.awt.Color(204, 204, 204));
        Separador2.setForeground(new java.awt.Color(204, 204, 204));
        Login.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        EnviarButton.setBackground(new java.awt.Color(120, 77, 60));
        EnviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        EnviarButton.setForeground(new java.awt.Color(255, 255, 255));
        EnviarButton.setText("Enviar");
        EnviarButton.setAlignmentX(20.0F);
        EnviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarButtonActionPerformed(evt);
            }
        });
        Login.add(EnviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        BarraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        BarraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        BarraSuperior.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        Minimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        BarraSuperior.add(Minimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\retroceder.png")); // NOI18N
        BarraSuperior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel38.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("ATRÁS");
        BarraSuperior.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        MenuCarta.setBackground(new java.awt.Color(255, 255, 255));
        MenuCarta.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        MenuCarta.setForeground(new java.awt.Color(120, 77, 60));
        MenuCarta.setText("MENÚ");
        MenuCarta.setBorder(null);
        MenuCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCartaActionPerformed(evt);
            }
        });
        BarraSuperior.add(MenuCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        getContentPane().add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        MENU.setBackground(new java.awt.Color(255, 255, 255));
        MENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel2.setText("Carta           Infantil");
        MENU.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 150, 30));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel3.setText("Nuestro Café");
        MENU.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 100, 30));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel4.setText("Platos         Especiales");
        MENU.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 40));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel5.setText("Carta         Dulce");
        MENU.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 51, 150, 40));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel6.setText("Carta         Salada");
        MENU.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 30));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel7.setText("3. Café Ristretto.............1´50€");
        MENU.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, -1));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel8.setText("1. Expresso......................1´20€");
        MENU.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 200, -1));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel9.setText("2. Cortado........................1´20€");
        MENU.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 200, -1));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel10.setText("6. Café con Leche............1´50€");
        MENU.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 200, -1));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel11.setText("4. Café Largo..................1´50€");
        MENU.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 200, -1));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setText("5. Latte Macchiato.........1´50€");
        MENU.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 200, -1));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setText("9. Café Bombón...............1´75€");
        MENU.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, -1));

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel14.setText("7. Capuccino....................1´50€");
        MENU.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 200, -1));

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel15.setText("8. Café Mocca.................1´50€");
        MENU.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 200, -1));

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel16.setText("12. Carajillo.....................1´75€");
        MENU.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 200, -1));

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel17.setText("10. Café Vienés...............1´75€");
        MENU.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 200, -1));

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel18.setText("11. Café Irlandés.............1´75€");
        MENU.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 200, -1));

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel19.setText("1. Pan sin Gluten");
        MENU.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 200, -1));

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel20.setText("2. Pastel de la casa ");
        MENU.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, -1));

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel21.setText("    sin azúcar..................2´00€");
        MENU.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 200, -1));

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel22.setText("Frescas Variadas......3´00€");
        MENU.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 200, -1));

        jLabel23.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel23.setText("    sin azúcar..................1´85€");
        MENU.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 200, -1));

        jLabel24.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel24.setText("1. Dónut Clásico..............1´50€");
        MENU.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, -1));

        jLabel25.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel25.setText("2. Dónut de Chocolate....1´70€");
        MENU.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, -1));

        jLabel26.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel26.setText("3. Dónut de Crema..........1´70€");
        MENU.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        jLabel27.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel27.setText("4. Gofre Clásico...............2´00€");
        MENU.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        jLabel28.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel28.setText("5. Crepé Dulce................2´00€");
        MENU.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, -1));

        jLabel29.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jLabel29.setText("- Dulce de Leche");
        MENU.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, -1));

        jLabel30.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel30.setText("Vegetal.......1´50€");
        MENU.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 200, -1));

        jLabel31.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel31.setText("3. Bocadillo Jamón............1´90€");
        MENU.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 220, -1));

        jLabel32.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel32.setText("4. Crepé Salado.................2´00€");
        MENU.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, -1));

        jLabel33.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel33.setText("York y Queso...............2´10€");
        MENU.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 210, -1));

        jLabel34.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel34.setText("13. Café Americano.........1´80€");
        MENU.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 200, -1));

        jLabel35.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel35.setText("14. Frappé.......................1´80€");
        MENU.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 200, -1));

        jLabel36.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel36.setText("15. Descafeinado............1´00€");
        MENU.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 200, -1));

        jLabel37.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel37.setText("16. Azteca..........1´50€");
        MENU.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 200, -1));

        jLabel39.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel39.setText("14. Avellana.......1´50€");
        MENU.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 200, -1));

        jLabel40.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel40.setText("16. Infusiones....1´00€");
        MENU.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 200, -1));

        jLabel41.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel41.setText("Mixto........1´50€");
        MENU.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, -1));

        jLabel42.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jLabel42.setText("Añade cualquier Topping por  2€:");
        MENU.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, -1));

        jLabel43.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jLabel43.setText("- Nutella");
        MENU.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, -1));

        jLabel44.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jLabel44.setText("- Chocolate Blanco");
        MENU.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, -1));

        jLabel45.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel45.setText("1. Sándwich");
        MENU.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 200, -1));

        jLabel46.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel46.setText("2. Sándwich");
        MENU.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 200, -1));

        jLabel47.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel47.setText("5. Croissant Jamón ");
        MENU.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 210, -1));

        jLabel48.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel48.setText("Menú Coffee Monster ");
        MENU.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 200, -1));

        jLabel49.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel49.setText("Infantil...........................4´00€");
        MENU.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 200, -1));

        jLabel50.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel50.setText("- Batido/Refresco/");
        MENU.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 200, -1));

        jLabel51.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel51.setText("- Producto Dulce ó Salado");
        MENU.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 200, -1));

        jLabel52.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel52.setText("- Juguete Coffee Monster");
        MENU.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 200, -1));

        jLabel53.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel53.setText("3. Cookies de Chocolate");
        MENU.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 200, -1));

        jLabel54.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel54.setText("5. Nuevo Menú Celíaco");
        MENU.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 200, -1));

        jLabel55.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel55.setText("15. Nube............1´50€");
        MENU.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 200, -1));

        jLabel56.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel56.setText("4. Macedonia de Frutas");
        MENU.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 200, -1));

        BackGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\Carta\\CartaModelo1.jpg")); // NOI18N
        MENU.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaBoxActionPerformed

    private void EnviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarButtonActionPerformed

    private void MenuCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCartaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel ContrasaeñaText;
    private javax.swing.JPasswordField ContraseñaBox;
    private javax.swing.JButton EnviarButton;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MENU;
    private javax.swing.JTextField MenuCarta;
    private javax.swing.JLabel MenuDesp;
    private javax.swing.JLabel Minimizar1;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JLabel UsuarioText;
    private javax.swing.JScrollPane UsuarioTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
