/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Telefonos extends javax.swing.JFrame {

    /**
     * Creates new form telefono
     */
    public Telefonos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        MenuDesp = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JLabel();
        UsuarioTextBox = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Separador1 = new javax.swing.JSeparator();
        ContrasaeñaText = new javax.swing.JLabel();
        ContraseñaBox = new javax.swing.JPasswordField();
        Separador2 = new javax.swing.JSeparator();
        EnviarButton = new javax.swing.JButton();
        BarraSuperior = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        Minimizar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        TelefonosTitulo = new javax.swing.JTextField();
        MenuTelefonos = new javax.swing.JPanel();
        BusqClienText = new javax.swing.JLabel();
        ClienteIcon = new javax.swing.JLabel();
        busqClientBox1 = new javax.swing.JScrollPane();
        BusqClient1 = new javax.swing.JTextPane();
        SeparadorBusqCliente = new javax.swing.JSeparator();
        BusquedaButton = new javax.swing.JButton();
        RegistroNuevoCliente = new javax.swing.JLabel();
        NewUserSymbol = new javax.swing.JLabel();
        RegistroText = new javax.swing.JLabel();
        RegistrodeClientes = new javax.swing.JScrollPane();
        RegistroScrollBar = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/menuhamburguesa.png"))); // NOI18N
        Login.add(MenuDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/96x96/logo.jpg"))); // NOI18N
        Login.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        UsuarioText.setBackground(new java.awt.Color(102, 51, 0));
        UsuarioText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UsuarioText.setForeground(new java.awt.Color(120, 77, 60));
        UsuarioText.setText("Usuario:");
        UsuarioText.setAlignmentX(20.0F);
        Login.add(UsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        UsuarioTextBox.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextPane1.setText("Ingrese su usuario o email");
        jTextPane1.setAlignmentX(20.0F);
        UsuarioTextBox.setViewportView(jTextPane1);

        Login.add(UsuarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 20));

        Separador1.setForeground(new java.awt.Color(204, 204, 204));
        Login.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 10));

        ContrasaeñaText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        ContrasaeñaText.setForeground(new java.awt.Color(120, 77, 60));
        ContrasaeñaText.setText("Contraseña:");
        ContrasaeñaText.setAlignmentX(20.0F);
        Login.add(ContrasaeñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        ContraseñaBox.setBackground(new java.awt.Color(255, 255, 255));
        ContraseñaBox.setText("jPasswordField1");
        ContraseñaBox.setAlignmentX(20.0F);
        ContraseñaBox.setBorder(null);
        ContraseñaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaBoxActionPerformed(evt);
            }
        });
        Login.add(ContraseñaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 20));

        Separador2.setBackground(new java.awt.Color(204, 204, 204));
        Separador2.setForeground(new java.awt.Color(204, 204, 204));
        Login.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 10));

        EnviarButton.setBackground(new java.awt.Color(120, 77, 60));
        EnviarButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        EnviarButton.setForeground(new java.awt.Color(255, 255, 255));
        EnviarButton.setText("Enviar");
        EnviarButton.setAlignmentX(20.0F);
        EnviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarButtonActionPerformed(evt);
            }
        });
        Login.add(EnviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 118, 41));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        BarraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        BarraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/cerrar.png"))); // NOI18N
        BarraSuperior.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        Minimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/minimizar.png"))); // NOI18N
        BarraSuperior.add(Minimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\retroceder.png")); // NOI18N
        BarraSuperior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel38.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("ATRÁS");
        BarraSuperior.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        TelefonosTitulo.setBackground(new java.awt.Color(255, 255, 255));
        TelefonosTitulo.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        TelefonosTitulo.setForeground(new java.awt.Color(120, 77, 60));
        TelefonosTitulo.setText("TELÉFONOS");
        TelefonosTitulo.setBorder(null);
        TelefonosTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonosTituloActionPerformed(evt);
            }
        });
        BarraSuperior.add(TelefonosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 50));

        MenuTelefonos.setBackground(new java.awt.Color(255, 255, 255));
        MenuTelefonos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BusqClienText.setBackground(new java.awt.Color(102, 51, 0));
        BusqClienText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        BusqClienText.setForeground(new java.awt.Color(120, 77, 60));
        BusqClienText.setText("Búsqueda de cliente:");
        BusqClienText.setAlignmentX(20.0F);
        MenuTelefonos.add(BusqClienText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        ClienteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafeteria/usuario (1).png"))); // NOI18N
        MenuTelefonos.add(ClienteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 130));

        busqClientBox1.setBorder(null);

        BusqClient1.setBackground(new java.awt.Color(255, 255, 255));
        BusqClient1.setBorder(null);
        BusqClient1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        BusqClient1.setText("Ingresar Nombre, Apellido, ID o teléfono");
        BusqClient1.setAlignmentX(20.0F);
        busqClientBox1.setViewportView(BusqClient1);

        MenuTelefonos.add(busqClientBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 290, 20));

        SeparadorBusqCliente.setForeground(new java.awt.Color(204, 204, 204));
        MenuTelefonos.add(SeparadorBusqCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 290, 10));

        BusquedaButton.setBackground(new java.awt.Color(120, 77, 60));
        BusquedaButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        BusquedaButton.setForeground(new java.awt.Color(255, 255, 255));
        BusquedaButton.setText("Buscar");
        BusquedaButton.setAlignmentX(20.0F);
        BusquedaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaButtonActionPerformed(evt);
            }
        });
        MenuTelefonos.add(BusquedaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 130, 41));

        RegistroNuevoCliente.setBackground(new java.awt.Color(102, 51, 0));
        RegistroNuevoCliente.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        RegistroNuevoCliente.setForeground(new java.awt.Color(120, 77, 60));
        RegistroNuevoCliente.setText("Registro de nuevo cliente:");
        RegistroNuevoCliente.setAlignmentX(20.0F);
        MenuTelefonos.add(RegistroNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 250, -1));

        NewUserSymbol.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\DAM\\2º DAM\\3. Desarrollo de Interfaces\\3. Proyecto Cafetería\\Recursos\\usuarionuevo2.png")); // NOI18N
        MenuTelefonos.add(NewUserSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        RegistroText.setBackground(new java.awt.Color(102, 51, 0));
        RegistroText.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        RegistroText.setForeground(new java.awt.Color(120, 77, 60));
        RegistroText.setText("Registro de clientes:");
        RegistroText.setAlignmentX(20.0F);
        MenuTelefonos.add(RegistroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));
        MenuTelefonos.add(RegistrodeClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 380, 430));
        MenuTelefonos.add(RegistroScrollBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 20, 430));

        getContentPane().add(MenuTelefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaBoxActionPerformed

    private void EnviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarButtonActionPerformed

    private void TelefonosTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonosTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonosTituloActionPerformed

    private void BusquedaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telefonos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JLabel BusqClienText;
    private javax.swing.JTextPane BusqClient1;
    private javax.swing.JButton BusquedaButton;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel ClienteIcon;
    private javax.swing.JLabel ContrasaeñaText;
    private javax.swing.JPasswordField ContraseñaBox;
    private javax.swing.JButton EnviarButton;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MenuDesp;
    private javax.swing.JPanel MenuTelefonos;
    private javax.swing.JLabel Minimizar1;
    private javax.swing.JLabel NewUserSymbol;
    private javax.swing.JLabel RegistroNuevoCliente;
    private javax.swing.JScrollBar RegistroScrollBar;
    private javax.swing.JLabel RegistroText;
    private javax.swing.JScrollPane RegistrodeClientes;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JSeparator SeparadorBusqCliente;
    private javax.swing.JTextField TelefonosTitulo;
    private javax.swing.JLabel UsuarioText;
    private javax.swing.JScrollPane UsuarioTextBox;
    private javax.swing.JScrollPane busqClientBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
